services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=1000               # ID пользователя
      - PGID=1000               # ID группы
      - VERSION=docker
      - TZ=Europe/Moscow
      - PLEX_CLAIM=        # Установите свой токен https://plex.tv/claim
    volumes:
      - ./config/plex:/config    # Путь для конфигурационных файлов Plex
      - /mnt/3T:/media           # Путь к вашим медиафайлам
    ports:
      - 32400:32400/tcp          # Порт для доступа к Plex Web UI
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: always
